// 5-7 harfli Türkçe kelime havuzu (temizlenmiş, küçük harf, şapkalı/özel harfler dahil)
// Not: Listede tekrarları engellemek için manuel gözden geçirildi.
export const TR_WORDS: string[] = [
  'aile', 'ailem', 'akort', 'akşam', 'alem', 'algın', 'altın', 'anlam', 'ansız', 'araba', 'aranj', 'arpac',
  'aslan', 'astar', 'aşina', 'aşure', 'atari', 'avize', 'aylar', 'aylık', 'aynen', 'ayran', 'ayval',
  'babam', 'badem', 'bagaj', 'bahar', 'bahçe', 'bahri', 'bakan', 'balık', 'balkı', 'bamba', 'bambu',
  'banka', 'barış', 'basit', 'basil', 'baski', 'bavul', 'bayat', 'bayır', 'beden', 'bekçi', 'belge',
  'belli', 'benek', 'beşik', 'beşli', 'bezin', 'biber', 'biçim', 'bilet', 'birik', 'birim', 'bitap',
  'bitek', 'biçki', 'biyel', 'bizen', 'bizim', 'bohem', 'bolca', 'bomba', 'borcu', 'borçl', 'boyun',
  'bozuk', 'böcek', 'bölge', 'bölük', 'bölüm', 'böyle', 'budak', 'bulak', 'buluş', 'burun', 'butik',
  'buyur', 'büfe', 'büyük', 'büyüt', 'büzük', 'cacık', 'camia', 'camlı', 'canci', 'canlı', 'cedit',
  'celal', 'cevap', 'cevri', 'ceviz', 'cezae', 'cezve', 'cılız', 'cimri', 'cirit', 'cüzdan', 'çadır',
  'çağrı', 'çakıl', 'çakma', 'çalar', 'çamur', 'çanak', 'çarşı', 'çatık', 'çavuş', 'çaycı', 'çehre',
  'çekek', 'çekiç', 'çelik', 'çello', 'çemen', 'çerez', 'çevik', 'çıban', 'çıkık', 'çıkma', 'çipil',
  'çizgi', 'çoban', 'çocuk', 'çukur', 'çürük', 'dadaş', 'dahil', 'daimi', 'dakik', 'dalga', 'damar',
  'damak', 'danış', 'davet', 'dayan', 'defne', 'defol', 'dekan', 'delik', 'demet', 'demir', 'deniz',
  'denge', 'denli', 'dergi', 'derin', 'derya', 'desen', 'devam', 'devre', 'devri', 'deyim', 'dibek',
  'diken', 'dikey', 'diler', 'dilim', 'dinar', 'dingo', 'dizgi', 'dizim', 'dobra', 'doğaç', 'doğal',
  'doğan', 'doğru', 'dokuz', 'dolap', 'dolgu', 'dolma', 'donda', 'donuk', 'dostu', 'doyum', 'düzen',
  'düşes', 'düşün', 'düşük', 'eceli', 'eczacı', 'edebi', 'edeni', 'ederi', 'eğmek', 'eğreti', 'eğris',
  'eğrik', 'eklem', 'ekmek', 'ekran', 'ekşi', 'ekser', 'eksik', 'ekzot', 'elbet', 'eller', 'emaye',
  'emekl', 'emici', 'emzik', 'enayi', 'enfes', 'engel', 'enlem', 'ensar', 'envai', 'ergen', 'ergin',
  'erkek', 'erkan', 'erkan', 'erkin', 'erzak', 'esans', 'esasi', 'esbak', 'esers', 'eskiz', 'esnaf',
  'espri', 'essay', 'ester', 'eşarp', 'eşlik', 'eşsiz', 'etkin', 'etnik', 'evcil', 'evham', 'evlat',
  'evrak', 'eylem', 'eyvah', 'fakir', 'falan', 'falso', 'fanus', 'fasik', 'fener', 'fenci', 'ferah',
  'ferağ', 'ferik', 'ferman', 'fersiz', 'fesat', 'fethe', 'fetva', 'fevri', 'fidan', 'fikir', 'final',
  'firar', 'fırça', 'fırın', 'fırtı', 'fiske', 'fiyat', 'fizik', 'fokur', 'forma', 'forum', 'fosep',
  'foto', 'frans', 'freze', 'fuaye', 'fuhuş', 'fular', 'funda', 'füsun', 'gabon', 'gadir', 'gafil',
  'gaye', 'gayet', 'gazap', 'gazel', 'gazoz', 'gebze', 'gecik', 'gelin', 'gelir', 'gemi', 'genel',
  'geniş', 'geode', 'gerçek', 'gergi', 'germe', 'gitar', 'gizem', 'göçer', 'göçük', 'göğüs', 'gölge',
  'gömle', 'gönül', 'görü', 'görev', 'gözet', 'gözü', 'gülme', 'gülüş', 'günce', 'günde', 'gündo',
  'güney', 'güruh', 'güven', 'haber', 'hacim', 'haciz', 'hakan', 'hakim', 'halat', 'halka', 'haluk',
  'hamle', 'hanım', 'hapis', 'harbi', 'harç', 'harek', 'harf', 'hasar', 'hatır', 'hatun', 'hayal',
  'hayat', 'hazan', 'hazır', 'hedef', 'helal', 'helez', 'hemen', 'henüz', 'hepsi', 'herif', 'heves',
  'hezim', 'hijyen', 'hile', 'hindi', 'hisar', 'hisse', 'hızlı', 'hürri', 'ıslak', 'ıslah', 'ısmar',
  'ışıld', 'ışını', 'ıtır', 'iade', 'ibare', 'ibraz', 'ibret', 'icmal', 'içeri', 'içkin', 'içsel',
  'içten', 'ideel', 'idman', 'ifade', 'ihbar', 'ihlal', 'ihsan', 'ihzar', 'ikame', 'ikbal', 'ikili',
  'iklim', 'ikmal', 'ikram', 'iksir', 'ilahi', 'ilave', 'ilgin', 'ilham', 'ilkel', 'iller', 'illet',
  'ilmek', 'imkan', 'imla', 'imlek', 'imrar', 'imtih', 'incek', 'incik', 'indir', 'infaz', 'inmek',
  'insan', 'inzal', 'iplik', 'irade', 'irket', 'irfan', 'ironi', 'ispat', 'israr', 'istek', 'istif',
  'istim', 'işlem', 'işsiz', 'itaat', 'ithal', 'itibar', 'itlaf', 'ivme', 'iyice', 'izhar', 'izlem',
  'izmar', 'izole', 'izzet', 'jäle', 'kabak', 'kabil', 'kablo', 'kadar', 'kadem', 'kadir', 'kafir',
  'kafes', 'kahır', 'kahve', 'kaka', 'kalem', 'kalın', 'kalkı', 'kalkı', 'kalıp', 'kalıt', 'kaman',
  'kamer', 'kamış', 'kanal', 'kanat', 'kanun', 'kapak', 'kapan', 'kapas', 'kaput', 'karar', 'karga',
  'kargo', 'karış', 'karlı', 'karne', 'karun', 'kaset', 'kase', 'kasım', 'kasko', 'kaslı', 'kasma',
  'katar', 'katil', 'katkı', 'katot', 'katre', 'kavak', 'kavga', 'kavil', 'kavrul', 'kayık', 'kayip',
  'kayit', 'kayma', 'kazak', 'kazanç', 'kazma', 'kebap', 'kedi', 'kehan', 'kekik', 'kelek', 'kelim',
  'keman', 'kemer', 'kemik', 'kents', 'kesek', 'kesik', 'kesim', 'kesin', 'kesit', 'kesti', 'keşif',
  'keşke', 'keten', 'kevgir', 'keyif', 'kezik', 'kibar', 'kibrit', 'kiler', 'kilim', 'kilit', 'kimse',
  'kına', 'kıran', 'kırma', 'kısas', 'kısım', 'kıyı', 'klima', 'koban', 'kobra', 'koca', 'kofre',
  'koku', 'kolaj', 'kolay', 'kombi', 'komik', 'kongo', 'konuk', 'konum', 'kopya', 'kopuk', 'korna',
  'korse', 'kosta', 'koşul', 'köfte', 'köprü', 'köşe', 'köşk', 'kredi', 'kroki', 'krom', 'kroşe',
  'kroml', 'kuduz', 'kulak', 'kulis', 'kulüp', 'kurak', 'kuram', 'kurgu', 'kurma', 'kurul', 'kurum',
  'kurye', 'kuşak', 'kutu', 'kuyum', 'kuzey', 'kuzin', 'küçük', 'kült', 'kümes', 'küpür', 'kürsü',
  'lahit', 'lakap', 'lamba', 'lazım', 'leble', 'legal', 'lehçe', 'lekes', 'lemur', 'leziz', 'lider',
  'lifli', 'ligde', 'liman', 'limit', 'lisan', 'liste', 'litre', 'lodos', 'lokal', 'lokum', 'lombo',
  'lorem', 'lorta', 'lotus', 'lüks', 'lütuf', 'mabet', 'macun', 'madde', 'maden', 'mağara', 'mahir',
  'mahkû', 'mahle', 'mahir', 'mahir', 'mahya', 'makam', 'makas', 'maket', 'makro', 'makul', 'malik',
  'mamut', 'manda', 'manev', 'manga', 'mango', 'manifesto', 'manik', 'mantar', 'mantı', 'maral',
  'marul', 'masal', 'maske', 'masum', 'matem', 'maviş', 'mayın', 'mayor', 'mazot', 'medya', 'mekan',
  'melik', 'melis', 'menfa', 'merak', 'mermi', 'mesai', 'mesaj', 'mesel', 'mesut', 'metal', 'metin',
  'metro', 'mevki', 'meyve', 'mezar', 'mezin', 'mimar', 'mimik', 'minik', 'misal', 'model', 'modül',
  'modern', 'modus', 'mola', 'moral', 'motel', 'motiv', 'motor', 'muhit', 'muzip', 'nabız', 'naçiz',
  'nafile', 'nakit', 'nakış', 'nalın', 'namaz', 'namlu', 'narin', 'nasip', 'nazik', 'nazlı', 'neden',
  'nefis', 'nehir', 'neler', 'nemli', 'nesil', 'nesne', 'neşet', 'nevri', 'neyse', 'niçin', 'niyet',
  'nisan', 'nisap', 'nispet', 'nitel', 'nitro', 'nişan', 'nişan', 'nizam', 'nokt', 'nuhus', 'nüfus',
  'oberj', 'obruk', 'ocak', 'odağa', 'odalı', 'ofans', 'ofset', 'oidip', 'okapi', 'okuma', 'okyan',
  'okyan', 'olası', 'oleik', 'olgun', 'olmak', 'oluru', 'olyan', 'omlet', 'onluk', 'onuru', 'opera',
  'organ', 'orhan', 'ortak', 'ortam', 'ortay', 'otlak', 'otluk', 'otluk', 'otops', 'otizm', 'oynak',
  'oyunc', 'oyunu', 'ozmoz', 'öbür', 'ödeme', 'ödemi', 'öğrenci', 'öğüt', 'öksüz', 'ölçek', 'ölçüm',
  'ölmek', 'ölmez', 'önlem', 'önlük', 'öpücük', 'örtü', 'örnek', 'örtme', 'örtük', 'öykü', 'özgül',
  'özgür', 'özlem', 'özlük', 'öznel', 'özsu', 'pabuç', 'paket', 'palet', 'palto', 'palya', 'pamuk',
  'panda', 'panel', 'panik', 'pante', 'papel', 'parça', 'parke', 'parla', 'parsa', 'parti', 'pasaj',
  'paten', 'patik', 'pazar', 'peçet', 'pekin', 'pekoz', 'pelin', 'pembe', 'pençe', 'perde', 'peron',
  'pesin', 'peste', 'pıtır', 'pilot', 'pimar', 'pison', 'pizza', 'plaka', 'planet', 'plaza', 'posta',
  'prens', 'print', 'proje', 'prova', 'psike', 'puan', 'pulpa', 'pulpa', 'puset', 'pusta', 'pürüz',
  'rafya', 'raket', 'rakım', 'ralli', 'ramak', 'rampa', 'rande', 'ranza', 'rapor', 'rasat', 'rasyo',
  'raylı', 'rehin', 'reklam', 'remen', 'resif', 'resim', 'reset', 'resmi', 'revak', 'reyal', 'rezil',
  'rıhtım', 'riayet', 'rijit', 'ritim', 'robot', 'roket', 'roman', 'rota', 'rotor', 'röfle', 'rötuş',
  'rüsum', 'sabır', 'sabit', 'sabun', 'sadık', 'sadun', 'safra', 'sahil', 'sahne', 'sahra', 'sahte',
  'sakız', 'sakin', 'salah', 'salep', 'salon', 'saman', 'saray', 'sargı', 'sarma', 'saten', 'satın',
  'savak', 'savaş', 'sayaç', 'sayfa', 'saygı', 'sayım', 'sazlı', 'seans', 'sebat', 'sebep', 'seçim',
  'sefer', 'sefil', 'seher', 'sehpa', 'sekme', 'seksi', 'selam', 'selim', 'semai', 'semen', 'semer',
  'semt', 'senet', 'serap', 'sergi', 'serin', 'serum', 'sesli', 'setir', 'seviş', 'sevki', 'sezar',
  'sıcak', 'sığır', 'sıkım', 'silik', 'silme', 'simge', 'simit', 'sinek', 'sinir', 'sivil', 'siyah',
  'skala', 'sobay', 'sokak', 'solak', 'soluk', 'somon', 'sonar', 'sonra', 'sorit', 'soğuk', 'soyad',
  'soylu', 'söğüt', 'sönük', 'sözde', 'sözel', 'söyle', 'sprey', 'stand', 'statu', 'stres', 'suçlu',
  'sufle', 'sulak', 'suluk', 'sunum', 'supap', 'sutlu', 'süper', 'sürat', 'sürüm', 'sürüş', 'sütun',
  'şahin', 'şakir', 'şalvar', 'şaman', 'şapka', 'şarap', 'şarkı', 'şarj', 'şehri', 'şehir', 'şeker',
  'şekil', 'şekli', 'şemsi', 'şenay', 'şeref', 'şeyma', 'şifre', 'şikay', 'şimdi', 'şirin', 'şubat',
  'şölen', 'şömine', 'şöyle', 'tahta', 'tahir', 'takım', 'taksi', 'takvi', 'talan', 'talep', 'talih',
  'tamam', 'tango', 'tanım', 'tanıt', 'tarih', 'tarım', 'tarla', 'tasar', 'tasdi', 'tatil', 'tatlı',
  'tavır', 'tavuk', 'tayin', 'tayfa', 'tayın', 'teker', 'teknik', 'tekne', 'telefon', 'temas', 'temel',
  'temiz', 'tempo', 'tenis', 'terbi', 'terfi', 'tesis', 'tesir', 'testi', 'tetik', 'teyze', 'tezat',
  'tımar', 'tıpa', 'tıraş', 'tıbbi', 'tıklım', 'tınak', 'tıpçı', 'tilki', 'timsah', 'tiner', 'titan',
  'tohum', 'tokat', 'tokyo', 'tonga', 'topak', 'topla', 'topuz', 'torna', 'torun', 'tozlu', 'trafik',
  'tranş', 'trend', 'tufan', 'tuhaf', 'tuli̇p', 'tuzak', 'tüfek', 'tülbent', 'tütün', 'tüvit', 'tüzük',
  'uçmak', 'uçsuz', 'uçurt', 'ufak', 'ufkun', 'uğrak', 'uğurlu', 'ulama', 'ultra', 'umumi', 'umut',
  'unvan', 'urban', 'usare', 'usanç', 'uskur', 'uslan', 'ustal', 'uyarı', 'uygar', 'uygul', 'uyruk',
  'uyuma', 'uzman', 'ücret', 'üçgen', 'üfleç', 'ülser', 'ülkü', 'ünvan', 'üreti', 'üslup', 'üstge',
  'ütopya', 'üzere', 'üzgün', 'üzmek', 'vaade', 'vakit', 'varak', 'vatan', 'vater', 'vebal', 'vefat',
  'vekil', 'veles', 'vergi', 'verim', 'veriş', 'veter', 'vezir', 'video', 'villa', 'viraj', 'vişne',
  'vites', 'vokal', 'volan', 'volta', 'votka', 'yağlı', 'yaşam', 'yaban', 'yabgu', 'yadig', 'yadır',
  'yalan', 'yalın', 'yalpa', 'yalva', 'yamaç', 'yamak', 'yapay', 'yapış', 'yapıt', 'yarım', 'yarış',
  'yasin', 'yatış', 'yavru', 'yayan', 'yazar', 'yazgı', 'yazım', 'yazma', 'yegân', 'yenge', 'yitik',
  'yıldız', 'yılgın', 'yıllık', 'yığın', 'yığın', 'yitme', 'yiyecek', 'yobaz', 'yolda', 'yolcu', 'yonga',
  'yonca', 'yöntem', 'yufka', 'yuhal', 'yular', 'yumak', 'yumru', 'yunus', 'yüreğ', 'yürür', 'yusuf',
  'yüzde', 'yüzük', 'zabit', 'zafır', 'zafer', 'zahir', 'zalim', 'zamir', 'zamlı', 'zango', 'zarar',
  'zaten', 'zayıf', 'zeban', 'zebra', 'zefir', 'zehir', 'zelil', 'zenci', 'zeka', 'zikir', 'zilli',
  'zirve', 'ziyad', 'ziyaf', 'zoe', 'zorla', 'zulüm'
];

export function pickRandomTRWord(minLen = 5, maxLen = 7): string {
  const pool = TR_WORDS.filter((w) => w.length >= minLen && w.length <= maxLen);
  return pool[Math.floor(Math.random() * pool.length)];
}


