name: Release from tag

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract latest changelog section for tag
        id: changelog
        shell: bash
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          echo "Preparing release notes for version ${TAG}"
          # Match headings like: ## 1.0.1, ### 1.0.1, ## [1.0.1], ### [1.0.1]
          awk -v ver="$TAG" '
            $0 ~ "^##+ \\[?" ver "\\]?" {print; flag=1; next}
            flag && /^##+ / {flag=0}
            flag {print}
          ' CHANGELOG.md > RELEASE_BODY.md || true
          if [ ! -s RELEASE_BODY.md ]; then
            echo "Changelog section for ${TAG} not found. Using placeholder body." > RELEASE_BODY.md
          fi
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: false
          body_path: RELEASE_BODY.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


